spring:
    cloud:
        stream:
            kafka:
                binder:
                    autoCreateTopics: false
                    brokers: localhost:9092
                    configuration:
                        auto.offset.reset: earliest

            bindings:
                kafkaNewEvent-out-0:
                    destination: kafka-new-event
                    content-type: application/json
                    group: kafka-ms
                    contentType: application/json


    function:
        definition: kafkaNewEvent